
class Status:
    UNDEFINED = -3
    ARRIVED = -2
    REJECTED = -1
    WAITING = 0
    ACCEPTED = 1
    FINISHED = 2

class ChargingStatus:
    UNKNOWN = -1
    UNPLUGGED = 0
    IN_CHARGING = 1
    IN_DISCHARGING = 2
    PREEMPTIVE_IN_CHARGING = 3
    PREEMPTIVE_HAS_CHARGED = 4
    PREEMPTIVE_IN_DISCHARGING = 5
    PREEMPTIVE_HAS_DISCHARGED = 6

